### ISSUE TITLE
POST /users

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#114]
# Acceptance Criteria
- [x] Given an application with this endpoint exists
- [x] When a POST request is made at this endpoint
- [x] Then all of the user data for a new user is added to the db

# Notes
Assume for now that user stats start null or zero and update as the user uploads more replays. Otherwise, information from all the replays the user appears in (even replays they did not upload themselves), needs to be collected.

**Comment by chrishollandaise** [comment]
I'd have to think about what exactly would be in the form, so stay tuned but this is the best you can do for now.
