### ISSUE TITLE
GET /users/{user_id}

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#115]
# Acceptance Criteria
- [x] Given an application with this endpoint exists
- [x] When a GET request is made at this endpoint
- [x] Then all of the user data for a particular user is returned

# Notes
One of the main purposes for getting user data from a specific user is to see statistical data including (but not limited to):
- wins, losses, win_loss_rate
- total_goals,  total_assists, total_saves, total_shots
- goal_average, assist_average, save_average, shot_average
- goal_shot_ratio

This list is subject to change, if we remember the number of replays the user is in and the total values, we can calculate averages and ratios.

**Comment by chrishollandaise** [comment]
Looks good. I think the only thing I would think about is what sort of information you can think of returning for that user. In terms of API design, it's good to only return "essential" things that define that user. So, for example, you wouldn't want to return the replays that the user exists, that would have to be another endpoint.

**Essential information about the user from the /users/{user_id} endpoint**
```JSON
{
  "id": "123456789",
  "name": "John Doe",
  "email": "johndoe@example.com",
  "created_at": "2022-01-01T00:00:00Z",
  "updated_at": "2022-01-02T00:00:00Z"
}
```

**(BAD EXAMPLE) Non-essential information about the user from the same endpoint**
```JSON
{
  "id": "123456789",
  "name": "John Doe",
  "email": "johndoe@example.com",
  "created_at": "2022-01-01T00:00:00Z",
  "updated_at": "2022-01-02T00:00:00Z",
  "replays": [
    {
      "id": "123",
      "map": "Hollywood",
      "hero": "Reinhardt",
      "duration": 1600,
      "result": "win"
    },
    {
      "id": "456",
      "map": "King's Row",
      "hero": "Ana",
      "duration": 2100,
      "result": "loss"
    }
}

```
