### ISSUE TITLE
PUT /users/{user_id}

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#116]
# Acceptance Criteria
- [x] Given an application with this endpoint exists
- [x] When a PUT request is made at this endpoint
- [x] Then a particular user's data is updated

# Notes
Mutable information would include user stats. This isn't something we want the user to manage themselves, we want to calculate it ourselves so some sort of permission is required. The general idea of data under the umbrella of stats is mentioned in story #115.

**Comment by chrishollandaise** [comment]
Remember, with puts it will receive a form that will have key-value pairs, the key being the field that want to change, and the value to change it to.
