### ISSUE TITLE
DELETE /users/{user_id}

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#117]
# Acceptance Criteria
- [x] Given an application with this endpoint exists
- [x] When a DELETE request is made at this endpoint
- [x] Then a particular user is removed from the system

# Notes
Not only do we need to consider what happens when a user or admin deletes a user, but also what happens if the same user is created again. Do we even want the user to be able to delete it? Maybe we just want the user to make their profile inactive.

**Comment by chrishollandaise** [comment]
Of course, this endpoint would need authentication. Only the user or an admin can delete a user's account.
