### ISSUE TITLE
[EPIC] Three-dimensional representation of an uploaded replay with a detailed timeline viewable via the website.

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#39]
## Description
A 3D viewer to visualize and playback a replay to the user. The replay scene will display the positions and orientations of cars as well as the ball's location at any given frame. Within the scene, the entire field is visible including the goal and boost pad placements. Additional optional data will also be provided such as boost and position markers. This replay viewer will serve the purpose of providing a method external to Rocket League's in-game viewer in which replays can be viewed by anyone. This will be useful in assisting players and coaches in analyzing Rocket League matches in a singular or cooperative setting. If Stratosphere is to stand out from the competition, it has to do what they do, but better.

## Story(s)
- #41 
- #48 
- #40 
- #28 
- #42

## Affected Personas
- Web developers who work on presenting the replay to the users
- Website users who get to view and share their replays

## What are we planning to do about it?
In order to complete this Epic, it will require a scene within the website that can be scaled and properly managed as a subcomponent within a much larger website. We need to acquire meshes for the ball and car; we need to accurately represent the ball size/shape and car type. It's important to consider various game modes and how the scene will change to accommodate varying arena shapes and goal locations. Ensuring quick loading times since we will require the fully parsed replay including all the network information may take time to load and render. Keeping all the information loaded is also important in the case of jumping quickly to different frames using the timeline as well as managing key moments on said timeline.

## How will we measure success?
Success will be achieved when we:
- Have a scene that can represent any frame in a replay
- The ability to playback through an entire replay
- A timeline that can control frames being displayed
- Relevant moments displayed on top of the timeline to help the user navigate the replay

**Comment by matt89201824** [comment]
I like the detail put into this. Two things to mention:
1. Are we definitively planning to allow the 3D capability to be able to account for different ball sizes and shapes, as well as different field shapes? Does Ballchasing allow for this?
2. I don't recall reading in this epic about having a movable camera. Is this something you wanted to include in the epic or not, potentially leaving it for the future?
